apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsapp-deployment
  labels:
    app: nodejsapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejsapp
  template:
    metadata:
      labels:
        app: nodejsapp
    spec:
      containers:
        - name: nodeserver
          image: namma14/nodeapp:latest
          ports:
            - containerPort: 3000

apiVersion: v1
kind: Service
metadata:
  name: nodejapp-service
spec:
  selector:
    app: nodejsapp
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 3000
      nodePort: 31110